### ISSUE TITLE
Support schema version 8

### ISSUE THREAD

**Issue by hvy** [sile/mlmd#5]
Similar to https://github.com/sile/mlmd/issues/3, but now the version was bumped to 8 in 1.7.0.

See https://github.com/google/ml-metadata/releases/tag/v1.7.0

**Comment by hvy** [comment]
Changes that might be of interest https://github.com/google/ml-metadata/commit/8772404b36bc75a868c5cc0c75acccb27612d7de

**Comment by sile** [comment]
@hvy Just FYI but I upgraded the support schema version to v8 in #6, and published mlmd-v0.3.0 and [mlmdquery-0.2.0](https://github.com/sile/mlmdquery/releases/tag/0.2.0).
If you have any troubles with the newer crate versions, please let me know.

**Comment by hvy** [comment]
Thanks for the quick fix. 🙇
Absolutely, I'll let you know when I've tried it out.

**Comment by hvy** [comment]
Tried it out a bit and it seems to work great so far. Again, thanks a lot!

**Comment by sile** [comment]
🎉
